baseURL: 'https://drumline.jsasd.org/'
title: JS Drumline
description: >-
  Jersey Shore Marching Band Drumline. Dut.
enableRobotsTXT: true
theme: compose
enableGitInfo: true

disableKinds:
  - taxonomy
  - taxonomyTerm

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  # Multiple docs directories
  docSections:
    - music

  # No sidebar on homepage
  uniqueHomePage: true

  blogDir: blog
  repo: 'https://github.com/JSASD/js-drumline'
  time_format_blog: 'Monday, January 02, 2006'
  time_format_default: 'January 2, 2006'

  # Maximum number of lines per codeblock, scrollable / expandable otherwise
  codeMaxLines: 7
  # Show codeblock line numbers
  codeLineNumbers: false

  # Darkmode default
  enableDarkMode: true

  author:
    name: Jersey Shore Area School District
    url: 'https://www.jsasd.org'
  
  logo:
    lightMode: images/2022DrumlineLogoLightMode.svg
    darkMode: images/2022DrumlineLogoDarkMode.svg
  
  source:
    name: GitHub
    iconLight: images/GitHubMarkLight.svg
    iconDark: images/GitHubMarkDark.svg
    url: 'https://github.com/JSASD/js-drumline'

menus:
  main:
    - name: Home
      weight: 1
      url: /

    - name: Music
      weight: 2
      url: music


markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      typographer: false
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: false
    style: monokai
    tabWidth: 2
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2
